# Use Node.js official lightweight image as a base
FROM node:16-alpine

# Set the working directory inside the container
WORKDIR /usr/src/app

# Copy app files into the container
COPY app.js .

# Command to run the application
CMD ["node", "app.js"]
